import './globals.css';

import { Inter, Space_Grotesk } from 'next/font/google';

const inter = Inter({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inter',
});

// eslint-disable-next-line @typescript-eslint/naming-convention
const space_grotesk = Space_Grotesk({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} font-sans  ${space_grotesk.variable} font-space`}
    >
      <body>{children}</body>
    </html>
  );
}
