import './globals.css';

import { Inter, Space_Grotesk } from 'next/font/google';


const inter = Inter({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-inter',
});

// eslint-disable-next-line @typescript-eslint/naming-convention
const space_grotesk = Space_Grotesk({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-space_grotesk',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <body className={`${inter.variable}, ${space_grotesk.variable}, font-sans`}>{children}</body>
    </html>
  );
}